name: Organization Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lumablossom
          template: classic
          base: header, repositories
          config_timezone: Europe/Berlin
          config_display: regular

          extras_css: |
            h1, h2, h3, h4, h5, h6 { color: #ff69b4 !important; } /* Hot Pink Headers */
            .field { color: #ff1493 !important; } /* Deep Pink Text */
            .icon { color: #ffb6c1 !important; fill: #ffb6c1 !important; } /* Light Pink Icons */
            div { color: #db7093; } /* Pale Violet Red for general text */
            .header { color: #ff69b4 !important; }

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_colors: "pink: #ffc0cb, pastel: #ffb6c1"
